triton-client: add triton-client http bindings for python
OE4T/meta-tegra-community pull request #48
Opened 2022-11-08 15:33 UTC by roger652

@ichergui Here is the master PR for the triton-client python bindings.

The changes are the same as in the `dunfell` branch except:
- the obvious adjustments for the new recipe syntax
- fixes for compiler issues in the `triton-python-backend` which were not present in `dunfell`.

2022-11-08 17:26 UTC, ichergui requested changes

2022-11-08 17:26 UTC, ichergui commented on recipes-devtools/triton/triton-client/0001-fix-cmake-build.patch
> ++cmake_minimum_required (VERSION 3.16)
I don't think that is needed to change the `cmake_minimum_required` here

2022-11-08 17:26 UTC, ichergui commented on recipes-devtools/triton/triton-client/0001-fix-cmake-build.patch
> ++cmake_minimum_required (VERSION 3.16)
Same as above

2022-11-08 17:26 UTC, ichergui commented on recipes-devtools/triton/triton-client/0001-fix-cmake-build.patch
> ++cmake_minimum_required (VERSION 3.16)
Same as above

2022-11-08 17:35 UTC, ichergui commented
@roger652 Thanks for the PR 
Overall looks good. please check my comments 
I think we don't have to change `cmake_minimum_required` because master branch provide a recent version anyway.

2022-11-09 12:20 UTC, roger652 commented
> @roger652 Thanks for the PR Overall looks good. please check my comments I think we don't have to change `cmake_minimum_required` because master branch provide a recent version anyway.

@ichergui You are right. The CMake minimum version only needs to be adjusted for the `dunfell` branch.
I removed all CMake version changes from the `triton-client` recipe.

2022-11-09 13:59 UTC, ichergui requested changes
I have a minor comment. Please fix it and I will approve the PR 
Thanks a lot @roger652  

I will may update the `SOURCE_DATE_EPOCH` in `triton_client` recipe. 
I will add you in PR review once I have one.

2022-11-09 13:59 UTC, ichergui commented on recipes-devtools/triton/triton-python-backend/0001-fix-cmake-build.patch
> ++cmake_minimum_required(VERSION 3.16)
@roger652 Could you please remove this line ?

2022-11-09 14:46 UTC, ichergui approved these changes

2022-11-09 15:24 UTC, merged